apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-config
data: 
  nginx-config: |
  events {}
  http {
    server {
      listen 80;
      location / {
        proxy_pass http://flask-app:550;
      }
    }
  }