apiVersion: v1
kind: Service
metadata: 
  name: flask-app
spec: 
  type: ClusterIP
  selector: 
    app: flask
  ports:
  - protocol: TCP
    port: 5500
    # targetPort: 5500
---
apiVersion: v1
kind: Pod
metadata: 
  name: flask
  labels:
    app: flask
spec: 
  containers: 
  - name: flask
    image: mcmuds/task1-app # Dockerhub
    imagePullPolicy: Always
    ports: 
    # - containerPort: 5500
    env:
    - name: YOUR_NAME
      value: QA Stuff